### ISSUE TITLE
Do i need docker?

### ISSUE THREAD

**Issue by microspino** [zzak/mruby-static#2]
In step to of [README](https://github.com/zzak/mruby-static/blob/master/README.md) you mention the use of docker-compose, I wonder if i could use this staticsitegen without any docker-thing.

**Comment by zzak** [comment]
You only need to use docker if you want to build your own binary.

But since I haven't released one yet, you will have to compile the app from source.

**Comment by zzak** [comment]
I want to finish a couple more TODOs before making a release, but feel free to compile the app from source if you want to experiment for now.
